language: php

php:
  - 7.1

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit

notifications:
  slack: orangejungle:Z8wSEiRSCqiv4Tl775uSl00H